# Site settings
title: Solace JMS API
summary: These tutorials get you up to speed sending and receiving messages with Solace technology.
baseurl: "/solace-samples-jms" # the subpath of your site, e.g. /solace-samples-java
repository: https://github.com/SolaceSamples/solace-samples-jms

# Also see _includes/intro.html to customize the description which gets included in index.html.

# Links
links-community: //solace.community
links-get-started: //solace.com/samples/solace-samples-jms/
links-downloads: //solace.com/downloads/
links-tech-other: //solace.com/products/tech/
links-java-tutorial: //solace.com/samples/solace-samples-java/topic-to-queue-mapping/
links-solaceCloud-setup: //solace.com/cloud/
docs-core-concepts: //docs.solace.com/PubSub-Basics/Core-Concepts.htm
docs-jms-home: //docs.solace.com/Solace-JMS-API/jms-get-started-open.htm
docs-jms-connections: //docs.solace.com/Solace-JMS-API/Establishing-Connections.htm
docs-jms-managing-sessions: //docs.solace.com/Solace-JMS-API/Managing-Sessions.htm
docs-jms-obtaining-connection-factories: //docs.solace.com/Solace-JMS-API/Obtaining-Connection-Fac.htm
docs-jms-working-with-destinations: //docs.solace.com/Solace-JMS-API/Working-with-Destination.htm
docs-jms-establishing-connections: //docs.solace.com/Solace-JMS-API/Obtaining-Connection-Fac.htm#establishing_connections_577400906_317143
docs-jms-properties-reference: //docs.solace.com/Solace-JMS-API/JMS-Properties-Reference.htm
docs-management-tools: //docs.solace.com/Management-Tools.htm
docs-management-soladmin: //docs.solace.com/SolAdmin/SolAdmin-Overview.htm?Highlight=SolAdmin
docs-management-cli: //docs.solace.com/Solace-CLI/Using-Solace-CLI.htm
docs-gm-rr: //docs.solace.com/Solace-JMS-API/Using-Topic-Requestors.htm
docs-topic-mapping: //docs.solace.com/PubSub-Basics/Core-Concepts.htm
docs-semp: //docs.solace.com/SEMP/Using-Legacy-SEMP.htm
docs-semp-get-started: //docs.solace.com/SEMP/SEMP-Get-Started.htm
